repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./setup.cfg
        language: system
        types: [ python ]
        pass_filenames: true
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black ./service --config pyproject.toml
        language: system
        types: [ python ]
        pass_filenames: true
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 --config ./setup.cfg
        language: system
        types: [ python ]
        pass_filenames: true
        files: ./service/.+\.py$
  - repo: local
    hooks:
      - id: flake8-tests
        name: flake8-tests
        entry: flake8 --config ./flake8.tests.ini
        language: system
        types: [ python ]
        pass_filenames: true
        files: tests/.+\.py$
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --config-file setup.cfg --ignore-missing-imports
        language: system
        types: [ python ]
        pass_filenames: true
        files: service/.+\.py$
